I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/intro.rpy", line 1, in script
    init python:
  File "game/intro.rpy", line 10, in <module>
    load_dotenv()
  File "game/intro.rpy", line 4, in load_dotenv
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kyatt/Desktop/uczelnia/magisterskie/masters-backup/GameAI/game/.env'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/intro.rpy", line 1, in script
    init python:
  File "F:\uczelnia\magister\PRACA DYPLOMOWA\renpy-8.2.0-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\uczelnia\magister\PRACA DYPLOMOWA\renpy-8.2.0-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/intro.rpy", line 10, in <module>
    load_dotenv()
  File "game/intro.rpy", line 4, in load_dotenv
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kyatt/Desktop/uczelnia/magisterskie/masters-backup/GameAI/game/.env'

Windows-10-10.0.19044 AMD64
Ren'Py 8.2.0.24012702
GameAI 1.0
Sun Feb 18 15:51:14 2024
